---
- name: request cert signing
  hosts: puppetagents
  gather_facts: true
  user: root
  roles:
  - {role: puppetagent}

- name: sign all client certs
  hosts: puppetmaster 
  gather_facts: true
  user: root
  roles:
  - {role: signcert}
